name: Build and Test
on: 
  push:
    branches:
      - master
  pull_request:

env:
  GO_VERSION: 1.17.5

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out source
        uses: actions/checkout@v2

      - name: Build
        run: make build

  test-cover:
    name: Unit coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out source
        uses: actions/checkout@v2

      - name: Test
        run: make unit-cover

      - name: Send top-level coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.txt

      - name: Send btcec
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: btcec/coverage.txt

      - name: Send btcutil coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: btcutil/coverage.txt

      - name: Send btcutil coverage for psbt package
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: btcutil/psbt/coverage.txt

  test-race:
    name: Unit race
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out source
        uses: actions/checkout@v2

      - name: Test
        run: make unit-race

  ostest:
    name: Cross test on GH operating systems
    needs: [build, test-cover, test-race] # only run if other jobs were succesfull
    strategy:
      matrix:
        os: [windows-2019, windows-2022, ubuntu-20.04, ubuntu-18.04, macos-11, macos-10.15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out source
        uses: actions/checkout@v2

      - name: Build
        run: make build
      
      - name: Test 
        run: make unit
      